# version: '3.9'
# services:
#   dev-database:
#     image: mongo
#     container_name: dev-database
#     ports:
#       - 27017: 27017
#     environment:
#       - MONGO_USERNAME: root
#       - MONGO_PASSWORD: Abc12345
#     networks:
#       - shop-networks
# networks:
#   shop-networks:

version: '3.9'
services:
  dev-database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false